### ISSUE TITLE
addon installation

### ISSUE THREAD

**Issue by kimatheplayful** [ImaginaryLandscape/django-newscenter#2]
Dear Landscape Team

I work for Divio AG and wanted to test your add-on on Django CMS to see if we should list it on the Django CMS market place (http://www.django-cms.org/en/addons/)
I tried to install the django-newscenter on Django CMS 3.0.14 with Django 1.7.9. The steps have been followed but if I enter manage.py migrate in the terminal  this appears ->

![migrate_error](https://cloud.githubusercontent.com/assets/13114899/9219059/521cce36-40d8-11e5-8210-1a295ea0de10.png)

The add-on shows up in the djangocms admin page but it doesn't work.

Any help would be appreciated.

**Comment by danrjohnson** [comment]
This looks like a `MIGRATION_MODULES` issue, did you add: `'newscenter': 'newscenter.migrations_django',` to your `MIGRATION_MODULES`?

**Comment by kimatheplayful** [comment]
yes I did. I tried to install it again but i got the same error.
